export default function BlogDetail ({ params }: { params: { slug: string } }) {
  return (
    <>
      <p>hello</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
      <p>hello{params.slug}</p>
    </>
  )
}
