import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";

const geistSans = Inter({
subsets:["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <head>
                <link rel="stylesheet" href="https://use.typekit.net/rbi5ydc.css" />
            </head>
      <body
        className={`${geistSans}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
